include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_single_quotes: true
    avoid_print: true
    always_use_package_imports: true
    prefer_final_fields: true
    use_super_parameters: true
    sort_constructors_first: true
    avoid_unnecessary_containers: true
    unnecessary_this: true
    avoid_classes_with_only_static_members: true